[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

# Ensure SPA routing works (fallback to index.html). Vite will copy public/_redirects, but we add safety here.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
